# Секция services описывает все контейнеры
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.auth
    ports:
      - "8001:8000"
    volumes:
      - ./auth-service:/app
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=auth_db
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - backend
    restart: always

  # --- Products Service ---
  products-service:
    build: ./products-service
    ports:
      - "8002:8000"
    volumes:
      - ./products-service:/app
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - POSTGRES_HOST=products-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=products_db
    depends_on:
      products-db:
        condition: service_healthy
      auth-service:
        condition: service_started
    networks:
      - backend
    restart: always

  chat-service:
    build: ./chat-service
    ports:
      - "8003:8000"
    volumes:
      - ./chat-service:/app
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - PRODUCTS_SERVICE_URL=http://products-service:8000
      - DB_HOST=chat-db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=chat_db
    depends_on:
      chat-db:
        condition: service_healthy
      auth-service:
        condition: service_started
      products-service:
        condition: service_started
    networks:
      - backend
    restart: always

  orders-service:
    build: ./orders-service
    ports:
      - "8004:8000"
    volumes:
      - ./orders-service:/app
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - PRODUCTS_SERVICE_URL=http://products-service:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@orders-db:5432/orders_db
    depends_on:
      orders-db:
        condition: service_healthy
      auth-service:
        condition: service_started
      products-service:
        condition: service_started
    networks:
      - backend
    restart: always

  rating-service:
    build: ./rating-service
    ports:
      - "8005:8000"
    volumes:
      - ./rating-service:/app
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - ORDERS_SERVICE_URL=http://orders-service:8000
      - DB_HOST=rating-db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=rating_db
    depends_on:
      rating-db:
        condition: service_healthy
      auth-service:
        condition: service_started
      orders-service:
        condition: service_started
    networks:
      - backend
    restart: always

  auth-db:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=auth_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "auth_db" ]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  products-db:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=products_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "products_db" ]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - products-db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  chat-db:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=chat_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "chat_db" ]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  orders-db:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=orders_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "orders_db" ]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  rating-db:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=rating_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "rating_db" ]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - rating-db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

# Определяем сети
networks:
  backend:
    driver: bridge

# Определяем volumes для сохранения данных БД
volumes:
  auth-db-data:
  products-db-data:
  chat-db-data:
  orders-db-data:
  rating-db-data:
