"""create_tables

Revision ID: fc2fb3a95049
Revises: 
Create Date: 2026-03-12 23:02:35.072156

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'fc2fb3a95049'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
